apiVersion: v2
name: polyfea-md-shell-samples
description: Sample applications and configurations for Polyfea MD Shell
type: application
version: 0.2.0
appVersion: "1.0"

dependencies:
  - name: polyfea-controller
    version: "0.4.0"
    repository: "https://polyfea.github.io/charts"
    condition: polyfea-controller.enabled
