# Default values for polyfea-md-shell-samples

# Enable or disable the deployment of sample resources
enabled: true

# Polyfea controller dependency configuration
polyfea-controller:
  # Set to false if polyfea-controller is already installed in another namespace
  enabled: true

# Enable or disable specific samples
samples:
  # Enable the Blue Marble Earth sample application
  earthSample: true

# Sample application configuration
mdShell:
  # Deployment settings
  replicaCount: 1
  image:
    repository: ghcr.io/polyfea/md-shell
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 7105
  
  resources:
    requests:
      memory: "16M"
      cpu: "0.01"
    limits:
      memory: "320M"
      cpu: "0.2"

  # Application headline
  applicationHeadline: "Polyfea Shell Application"

# MicroFrontendClass configuration
microfrontendClass:
  baseUri: "/fea"
  title: "Polyfea Microfrontend MD Shell"
  appName: "Polyfea MD Shell"
  iconUrl: "https://avatars.githubusercontent.com/u/154217229?s=400&u=ae64608e9686a2405680676a15800dc2b6df32bb&v=4"
