apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "polyfea-controller.fullname" . }}-leader-election
  labels:
    {{- include "polyfea-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "polyfea-controller.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "polyfea-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
