{{- if .Values.rbacRoles.createAdminRole }}
# This rule is not used by the project polyfea-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over polyfea.github.io resources.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "polyfea-controller.fullname" . }}-microfrontend-admin
  labels:
    {{- include "polyfea-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontends
  verbs:
  - '*'
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontends/status
  verbs:
  - get
{{- end }}
