apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "polyfea-controller.fullname" . }}-manager
  labels:
    {{- include "polyfea-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "polyfea-controller.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "polyfea-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
