{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyfea-md-shell
  labels:
    {{- include "polyfea-md-shell-samples.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mdShell.replicaCount }}
  selector:
    matchLabels:
      pod: polyfea-md-shell
      {{- include "polyfea-md-shell-samples.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        pod: polyfea-md-shell
        {{- include "polyfea-md-shell-samples.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: polyfea-md-shell
        image: "{{ .Values.mdShell.image.repository }}:{{ .Values.mdShell.image.tag }}"
        imagePullPolicy: {{ .Values.mdShell.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.mdShell.service.targetPort }}
        resources:
          {{- toYaml .Values.mdShell.resources | nindent 10 }}
{{- end }}
